In [1]:
import pandas as pd

df = pd.read_csv("../feature-engineering/output/dataset_churn_features.csv")

print("Linhas:", len(df))
print("Colunas:", len(df.columns))

df.head()

Linhas: 500
Colunas: 14

,cliente_id,total_atendimentos,total_gasto,ticket_medio,dias_desde_ultimo_atendimento,intervalo_medio_atendimentos,atendimentos_30d,atendimentos_90d,gasto_90d,quantidade_servicos_diferentes,quantidade_profissionais_diferentes,target_churn,atraso_vs_intervalo_medio,atraso_percentual
0,mock-cli-00001,1,162.48,162.48,99,0.00,0,0,0.00,1,1,1,99.00,0.000000
1,mock-cli-00002,7,1495.73,213.68,3,61.50,1,2,147.79,8,5,0,-58.50,-0.951220
2,mock-cli-00003,0,0.00,0.00,-1,0.00,0,0,0.00,0,0,1,-1.00,0.000000
3,mock-cli-00004,0,0.00,0.00,-1,0.00,0,0,0.00,0,0,1,-1.00,0.000000
4,mock-cli-00005,7,1208.66,172.67,1,53.67,1,2,811.75,7,5,0,-52.67,-0.981368

In [2]:
print(df["target_churn"].value_counts())

print("\nProporção:")
print(df["target_churn"].value_counts(normalize=True))

target_churn
0    326
1    174
Name: count, dtype: int64

Proporção:
target_churn
0    0.652
1    0.348
Name: proportion, dtype: float64

In [3]:
features_modelo_a = [
    "total_atendimentos",
    "total_gasto",
    "ticket_medio",
    "dias_desde_ultimo_atendimento",
    "intervalo_medio_atendimentos",
    "atendimentos_30d",
    "atendimentos_90d",
    "gasto_90d"
]

comparacao = df.groupby("target_churn")[features_modelo_a].mean().T

comparacao

target_churn                            0           1
total_atendimentos               3.177914    2.057471
total_gasto                    647.098681  357.464310
ticket_medio                   138.518466  114.319885
dias_desde_ultimo_atendimento   33.481595   43.316092
intervalo_medio_atendimentos    32.786595   38.237414
atendimentos_30d                 0.407975    0.287356
atendimentos_90d                 1.141104    0.643678
gasto_90d                      243.986595  104.608276

In [4]:
df[features_modelo_a].isnull().sum()

total_atendimentos               0
total_gasto                      0
ticket_medio                     0
dias_desde_ultimo_atendimento    0
intervalo_medio_atendimentos     0
atendimentos_30d                 0
atendimentos_90d                 0
gasto_90d                        0
dtype: int64

In [5]:
df[features_modelo_a].describe().T

,count,mean,std,min,25%,50%,75%,max
total_atendimentos,500.0,2.78800,2.945574,0.0,0.0,2.000,4.0000,14.00
total_gasto,500.0,546.30592,702.096239,0.0,0.0,271.015,806.0850,3886.82
ticket_medio,500.0,130.09736,120.422077,0.0,0.0,125.120,190.9725,813.75
dias_desde_ultimo_atendimento,500.0,36.90400,53.107472,-1.0,-1.0,18.000,49.0000,350.00
intervalo_medio_atendimentos,500.0,34.68348,39.309818,0.0,0.0,31.320,59.5000,244.00
atendimentos_30d,500.0,0.36600,0.494503,0.0,0.0,0.000,1.0000,2.00
atendimentos_90d,500.0,0.96800,1.008469,0.0,0.0,1.000,2.0000,4.00
gasto_90d,500.0,195.48294,287.521517,0.0,0.0,76.360,267.4775,1807.73

In [6]:
# existe vazamento de informações (Data leakage)
print(df[features_modelo_a + ["target_churn"]].corr()["target_churn"].sort_values())

atendimentos_90d                -0.235187
gasto_90d                       -0.231139
total_gasto                     -0.196699
total_atendimentos              -0.181371
atendimentos_30d                -0.116304
ticket_medio                    -0.095815
intervalo_medio_atendimentos     0.066116
dias_desde_ultimo_atendimento    0.088297
target_churn                     1.000000
Name: target_churn, dtype: float64